### ISSUE TITLE
Implement running backend in docker

### ISSUE THREAD

**Issue by canab** [oleksiistepaniak/wecan-tic-tac-toe-game#3]
### Makefile:
add task "up"

### docker-compose:
- mongo
- backend

### docker file
- Based on node:16-alpine

**Comment by canab** [comment]
```
  mongo_dhost:
    image: "mongo:5.0"
    container_name: "hutshub_mongo_dhost"
    volumes:
    - "./mongo/dhost/replica-init.js:/docker-entrypoint-initdb.d/replica-init.js"
    - "./mongo/dhost/hosts:/etc/hosts"
    command:
    ## required for mongo 4
    # - "--enableMajorityReadConcern=false"
    - "--replSet"
    - "rs0"
    ports:
    - "127.0.0.1:27017:27017"

  mongo_lhost:
    image: "mongo:5.0"
    container_name: "hutshub_mongo_lhost"
    volumes:
    - "./mongo/lhost/replica-init.js:/docker-entrypoint-initdb.d/replica-init.js"
    command:
    ## required for mongo 4
    # - "--enableMajorityReadConcern=false"
    - "--replSet"
    - "rs0"
    ports:
    - "127.0.0.1:27017:27017"

```
